"""Deterministic README, category index and complete catalog export."""
import argparse
import hashlib
import html
import json
import re
from pathlib import Path
from catalog import ROOT, load_entries, read_json, prompt_for


def dump(value):
    return json.dumps(value, ensure_ascii=False, indent=2) + '\n'


def text(value):
    return re.sub(r'([\\`*_{}\[\]()#+!|])', r'\\\1', html.escape(value, quote=False))


def localized(values, locale):
    return values.get(locale) or values['en']


def fenced(prompt):
    longest = max([len(m.group()) for m in re.finditer(r'`+', prompt)] + [2])
    fence = '`' * (longest + 1)
    return fence + 'text\n' + prompt + '\n' + fence


def render_readme(entries, taxonomy, locale):
    zh = locale == 'zh'
    heading = 'Awesome GPT Image 2.5 Prompts'
    intro = ('收集 GPT Image 2.5 的创作提示词与作品，按用途、风格和主体浏览。每个作品都附有完整提示词、作者、原帖和图片链接。'
             if zh else 'A collection of GPT Image 2.5 prompts and artwork, organized by use, style and subject. Each artwork includes its complete prompt, author, original post and image links.')
    lines = ['<!-- Generated by scripts/generate.py from content/. -->', '# ' + heading, '', '[English](README.md) · [简体中文](README.zh-CN.md)', '', intro, '',
             (f'**{len(entries)} 个作品** · ' if zh else f'**{len(entries)} artworks** · ') + '[Submit a prompt / 投稿](https://github.com/BravoNeo/awesome-gpt-image-2-5-prompts/issues/new?template=submit-prompt.yml)', '',
             ('替换提示词中的方括号变量，再粘贴到你使用的 GPT Image 2.5 工具。图像编辑类作品需要参考图片。' if zh else 'Replace bracketed variables, then paste a prompt into your GPT Image 2.5 tool. Image-editing prompts require a reference image.'), '',
             ('## 分类浏览' if zh else '## Browse categories'), '']
    for axis in ['use', 'style', 'subject']:
        lines += [('### ' + {'use':'用途','style':'风格','subject':'主体'}[axis]) if zh else '### ' + axis.title(), '', '| ' + ('分类 | 作品 | JSON |' if zh else 'Category | Artworks | JSON |'), '| --- | ---: | --- |']
        for key, label in taxonomy[axis].items():
            count = sum(key in e['categories'][axis] for e in entries)
            lines.append(f'| {text(localized(label, locale))} | {count} | [JSON](references/{axis}/{key}.json) |')
        lines.append('')
    lines += ['## ' + ('作品与提示词' if zh else 'Artwork & prompts'), '']
    for e in entries:
        prompt, language, fallback = prompt_for(e, locale)
        lines += [f'<a id="{e["slug"]}"></a>', '### ' + text(localized(e['title'], locale)), '', text(localized(e['description'], locale)), '',
                  ('作者：' if zh else 'By ') + text(e['author']['name']) + ((' (@' + text(e['author']['handle']) + ')') if e['author'].get('handle') else '') + ' · [' + ('原帖' if zh else 'Original post') + '](' + e['sourceUrl'] + ')', '',
                  ('类型：' if zh else 'Kind: ') + e['promptKind'] + ' · ' + text(e['inputRequirement']), '']
        if e.get('mediaSourceUrl') and e['mediaSourceUrl'] != e['sourceUrl']:
            lines += [('图片原帖：' if zh else 'Artwork source: ') + '[' + ('作者引用的输出作品' if zh else 'Author-quoted output artwork') + '](' + e['mediaSourceUrl'] + ')', '']
        output = next(m for m in e['media'] if m['role'] == 'output')
        lines += [f'![{text(output["alt"])}]({output["url"]})', '', ' · '.join(f'[{m["role"]} {i + 1}]({m["url"]})' for i,m in enumerate(e['media'])), '',
                  '<details>', '<summary>' + (('提示词原文 (' if fallback else '提示词 (') if zh else ('Original prompt (' if fallback else 'Prompt (')) + language + ')</summary>', '', fenced(prompt), '', '</details>', '']
    lines += ['## ' + ('投稿与使用数据' if zh else 'Contribute & use the data'), '',
              ('通过 [Issue 表单](https://github.com/BravoNeo/awesome-gpt-image-2-5-prompts/issues/new?template=submit-prompt.yml) 投稿，或按 [CONTRIBUTING](CONTRIBUTING.md) 提交 JSON。维护者标记 `approved` 后，Actions 会生成待审 JSON，合入内容后自动更新目录。' if zh else 'Submit via the [issue form](https://github.com/BravoNeo/awesome-gpt-image-2-5-prompts/issues/new?template=submit-prompt.yml), or contribute JSON following [CONTRIBUTING](CONTRIBUTING.md). When a maintainer labels an issue `approved`, Actions prepares a JSON artifact for review. Merged content automatically updates the catalog.'), '',
              ('页面与工具可读取 [完整导出](export/catalog.json) 和 [分类清单](references/manifest.json)。结构与命令见 [数据文档](docs/data-contract.md)。' if zh else 'Pages and tools can read the [complete export](export/catalog.json) and [category manifest](references/manifest.json). See the [data contract](docs/data-contract.md) for the structure and commands.'), '',
              '## ' + ('归属与许可' if zh else 'Attribution & licenses'), '',
              ('仓库代码采用 [MIT](LICENSE)。第三方提示词和图片归各自作者所有；图片保留公开来源链接。引用及进一步使用请遵循原作者授权，详见 [内容归属说明](CONTENT_RIGHTS.md)。' if zh else 'Repository code is [MIT licensed](LICENSE). Third-party prompts and artwork belong to their authors; images retain public source links. Follow the original author’s permissions for further use; see [content rights](CONTENT_RIGHTS.md).'), '',
              ('信息架构参考 [YouMind 的提示词合集](https://github.com/YouMind-OpenLab/awesome-gpt-image-2) 与分类搜索项目；本仓库由 BravoNeo 独立维护。' if zh else 'The information architecture is inspired by [YouMind’s prompt collection](https://github.com/YouMind-OpenLab/awesome-gpt-image-2) and category-search project. Independently maintained by BravoNeo.'), '']
    return '\n'.join(lines)


def build_outputs(entries=None):
    entries = load_entries() if entries is None else entries
    entries = sorted(entries, key=lambda e: e['id'])
    taxonomy = read_json(ROOT / 'content/taxonomy.json')
    outputs = {}
    full = []
    for entry in entries:
        item = dict(entry)
        item['originalPromptSha256'] = hashlib.sha256(entry['originalPrompt'].encode()).hexdigest()
        item['localizedPrompts'] = {locale: dict(zip(['text','language','fallback'], prompt_for(entry, locale))) for locale in ['en','zh']}
        full.append(item)
    outputs['export/catalog.json'] = dump({'schemaVersion':1, 'model':'GPT Image 2.5', 'count':len(entries), 'entries':full})
    categories = []
    for axis, options in taxonomy.items():
        for key, labels in options.items():
            items = [e for e in entries if key in e['categories'][axis]]
            path = f'references/{axis}/{key}.json'
            outputs[path] = dump({'schemaVersion':1,'model':'GPT Image 2.5','axis':axis,'category':key,'labels':labels,'count':len(items),'entryIds':[e['id'] for e in items]})
            categories.append({'axis':axis,'category':key,'labels':labels,'count':len(items),'path':path})
    for locale, path in [('en','README.md'),('zh','README.zh-CN.md')]:
        outputs[path] = render_readme(entries, taxonomy, locale)
    hashes = {path:hashlib.sha256(value.encode()).hexdigest() for path,value in sorted(outputs.items())}
    outputs['references/manifest.json'] = dump({'schemaVersion':1,'model':'GPT Image 2.5','totalArtworks':len(entries),'catalog':'export/catalog.json','categories':categories,'sha256':hashes})
    return outputs


def generate(check=False):
    outputs = build_outputs()
    expected = set(outputs)
    actual = {str(p.relative_to(ROOT)) for folder in ['references','export'] for p in (ROOT/folder).rglob('*.json')}
    stale = actual - expected
    changed = [name for name,value in outputs.items() if not (ROOT/name).exists() or (ROOT/name).read_text(encoding='utf-8') != value]
    if check:
        if stale or changed:
            raise ValueError(f'Generated files are stale: {sorted(stale | set(changed))}; run python3 scripts/generate.py')
    else:
        for name in stale:
            (ROOT/name).unlink()
        for name,value in outputs.items():
            target = ROOT/name
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(value, encoding='utf-8')
    print(f'{"Checked" if check else "Generated"} {len(outputs)} files')


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    generate(parser.parse_args().check)
